---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jupyterbook
spec:
  params:
    - name: url
      type: string
    - name: ref
      type: string
      default: ""
    - name: googleAnalyticsToken
      default: ""

  results:
    - name: url
      value: "$(tasks.url-to-results.results.output-result)"

  workspaces:
    - name: data

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: data
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.ref)

    - name: metrics-start
      taskRef:
        name: metrics-start
      params:
        - name: pipeline
          value: $(context.pipeline.name)
        - name: pipelineRun
          value: $(context.pipelineRun.name)

    - name: generate
      taskRef:
        name: generate-jupyterbook
      runAfter:
        - git-clone
        - metrics-start
      workspaces:
        - name: source
          workspace: data

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - generate
      workspaces:
        - name: source
          workspace: data
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - buildah
      params:
        - name: SCRIPT
          value: |
            cat <<EOM | oc apply -f -
            ---
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: $(context.pipelineRun.name)
              labels:
                app: $(context.pipelineRun.name)
              ownerReferences:
                - apiVersion: tekton.dev/v1beta1
                  blockOwnerDeletion: true
                  controller: true
                  kind: PipelineRun
                  name: $(context.pipelineRun.name)
                  uid: $(context.pipelineRun.uid)
            spec:
              selector:
                matchLabels:
                  app: $(context.pipelineRun.name)
              replicas: 1
              template:
                metadata:
                  labels:
                    app: $(context.pipelineRun.name)
                spec:
                  containers:
                    - name: $(context.pipelineRun.name)
                      image: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
                      resources:
                        limits:
                          cpu: 100m
                          memory: 100Mi
                      env:
                        - name: GA_TRACKING_ID
                          value: $(params.googleAnalyticsToken)
            ---
            apiVersion: v1
            kind: Service
            metadata:
              name: $(context.pipelineRun.name)
              ownerReferences:
                - apiVersion: tekton.dev/v1beta1
                  blockOwnerDeletion: true
                  controller: true
                  kind: PipelineRun
                  name: $(context.pipelineRun.name)
                  uid: $(context.pipelineRun.uid)
            spec:
              selector:
                app: $(context.pipelineRun.name)
              ports:
                - name: http
                  protocol: TCP
                  port: 8080
                  targetPort: 8080
            ---
            apiVersion: route.openshift.io/v1
            kind: Route
            metadata:
              name: $(context.pipelineRun.name)
              ownerReferences:
                - apiVersion: tekton.dev/v1beta1
                  blockOwnerDeletion: true
                  controller: true
                  kind: PipelineRun
                  name: $(context.pipelineRun.name)
                  uid: $(context.pipelineRun.uid)
            spec:
              to:
                kind: Service
                name: $(context.pipelineRun.name)
              port:
                targetPort: http
            ---
            kind: ImageStream
            apiVersion: image.openshift.io/v1
            metadata:
              name: $(context.pipelineRun.name)
              ownerReferences:
                - apiVersion: tekton.dev/v1beta1
                  blockOwnerDeletion: true
                  controller: true
                  kind: PipelineRun
                  name: $(context.pipelineRun.name)
                  uid: $(context.pipelineRun.uid)
            EOM
            oc wait --for=condition=available --timeout=600s deployment/$(context.pipelineRun.name)

    - name: url-to-results
      taskRef:
        name: oc-actions
      runAfter:
        - deploy
      params:
        - name: SCRIPT
          value: |
            echo "http://$(oc get route $(context.pipelineRun.name) --template='{{ .spec.host }}')" > $(results.output-result.path)

    - name: metrics-end
      taskRef:
        name: metrics-end
      runAfter:
        - buildah
      workspaces:
        - name: source
          workspace: data
      params:
        - name: pipeline
          value: $(context.pipeline.name)
        - name: pipelineRun
          value: $(context.pipelineRun.name)
