---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - metrics-start.yaml
    - metrics-end.yaml
    - generate-jupyterbook.yaml
    - generate-jupyterhub.yaml
    - oc-actions.yaml
