---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: ubi8-py38-sample-2 # TODO
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CNBi-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: ubi8-py38-sample-3
    opendatahub.io/notebook-image-desc: a Notebook with Python 3.8 and pandas and boto3
    opendatahub.io/notebook-image-creator: goern
spec:
  buildType: PackageList
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  packageVersions:
    - pandas
    - boto3>=1.24.0
