---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: ubi8-py38-sample-1
spec:
  dashboardInformation:
    name: ubi8-py38
    creator: meteor
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: s2i-thoth-ubi8-py39-baseimage-sample-1
spec:
  dashboardInformation:
    name: s2i-thoth-ubi8-py39
    creator: thoth-station
  runtimeEnvironment:
    baseImage: quay.io/thoth-station/s2i-thoth-ubi8-py39:v0.34.1
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: ubi8-py38-sample-2
spec:
  dashboardInformation:
    name: ubi8-py38-2
    creator: meteor
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  packageVersions:
    - "pandas"
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: ubi8-py38-sample-3
spec:
  dashboardInformation:
    name: ubi8-py38-3
    creator: meteor
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  packageVersions:
    - pandas
    - boto3>=1.24.0
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: s2i-minimal-py38-notebook
spec:
  dashboardInformation:
    name: s2i-minimal-py38-notebook
    creator: meteor
  strategy:
    type: import
    from: quay.io/thoth-station/s2i-minimal-py38-notebook:v0.2.2
