---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: s2i-minimal-py38-sample-1 # TODO
  labels:
    # Orignal, : and / need to be replaced! app.kubernetes.io/created-by: cpe:/a:meteor.zone:CNBi:v0.1.0
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CNBi-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: py38-1
    opendatahub.io/notebook-image-desc: Build using a S2I Python 3.8 image and a list of packages
    opendatahub.io/notebook-image-creator: codificat
spec:
  buildType: PackageList
  baseImage: quay.io/thoth-station/s2i-minimal-py38-notebook:v0.2.2
  packageVersions:
    - pandas
    - boto3>=1.24.0
---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: ubi9-py39-sample-1 # TODO
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CNBi-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: ubi9py39-1
    opendatahub.io/notebook-image-desc: Build using a list of packages, ontop a UBI9 Python 3.9 base image
    opendatahub.io/notebook-image-creator: codificat
spec:
  buildType: PackageList
  runtimeEnvironment:
    osName: rhel
    osVersion: "9"
    pythonVersion: "3.9"
  packageVersions:
    - "pandas"
---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: ubi8-py38-sample-2 # TODO
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CNBi-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: ubi8-py38-sample-3
    opendatahub.io/notebook-image-desc: a Notebook with Python 3.8 and pandas and boto3
    opendatahub.io/notebook-image-creator: goern
spec:
  buildType: PackageList
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  packageVersions:
    - pandas
    - boto3>=1.24.0
---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: elyra-aidevsecops-tutorial
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CNBi-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: Elyra DevSecOps Tutorial
    opendatahub.io/notebook-image-desc: Build from the Elyra Tutorial
    opendatahub.io/notebook-image-creator: codificat
spec:
  buildType: GitRepository
  repository: https://github.com/AICoE/elyra-aidevsecops-tutorial
  gitRef: master
