---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: ubi8-py38-sample-2
spec:
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  strategy:
    type: packageList
  packageVersions:
    - "pandas"
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: ubi8-py38-sample-3
  labels:
    app.kubernetes.io/created-by: cpe:/a:meteor.zone:CNBi:v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: ubi8-py38-sample-3
    opendatahub.io/notebook-image-desc: a Notebook with Python 3.8 and pandas and boto3
    opendatahub.io/notebook-image-creator: goern
spec:
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  strategy:
    type: packageList
  packageVersions:
    - pandas
    - boto3>=1.24.0
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: s2i-minimal-py38-notebook
  labels:
    app.kubernetes.io/created-by: cpe:/a:meteor.zone:CNBi:v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: s2i-minimal-py38-notebook
    opendatahub.io/notebook-image-desc: minimal notebook image for python 3.8
    opendatahub.io/notebook-image-creator: goern
spec:
  strategy:
    type: import
    from: quay.io/thoth-station/s2i-minimal-py38-notebook:v0.2.2
